$(document).ready(function() {

    $('.container').click(function() {
        $('#moveit').animate({
         'marginLeft' : "-350px"//moves left
        });
    });
    
    $('#cont1').click(function() {
     	$("#e1").show();
	$("#e111").show();
    	$("#e112").hide();
	$("#e113").hide();
	$("#e114").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e11').css("borderBottom","0px").animate({	});
	$('#e12').css("borderBottom", "1px solid #000000").animate({    });
	$('#e13').css("borderBottom", "1px solid #000000").animate({    });
	$('#e14').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont2').click(function() {
     	$("#e1").hide();
        $("#e2").show();
	$("#e221").show();
    	$("#e222").hide();
	$("#e223").hide();
	$("#e224").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e21').css("borderBottom","0px").animate({	});
	$('#e22').css("borderBottom", "1px solid #000000").animate({    });
	$('#e23').css("borderBottom", "1px solid #000000").animate({    });
	$('#e24').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont3').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").show();
	$("#e331").show();
    	$("#e332").hide();
	$("#e333").hide();
	$("#e334").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e31').css("borderBottom","0px").animate({	});
	$('#e32').css("borderBottom", "1px solid #000000").animate({    });
	$('#e33').css("borderBottom", "1px solid #000000").animate({    });
	$('#e34').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont4').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").show();
	$("#e441").show();
    	$("#e442").hide();
	$("#e443").hide();
	$("#e444").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e41').css("borderBottom","0px").animate({	});
	$('#e42').css("borderBottom", "1px solid #000000").animate({    });
	$('#e43').css("borderBottom", "1px solid #000000").animate({    });
	$('#e44').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont5').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").show();
	$("#e551").show();
    	$("#e552").hide();
	$("#e553").hide();
	$("#e554").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e51').css("borderBottom","0px").animate({	});
	$('#e52').css("borderBottom", "1px solid #000000").animate({    });
	$('#e53').css("borderBottom", "1px solid #000000").animate({    });
	$('#e54').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont6').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").show();
	$("#e661").show();
    	$("#e662").hide();
	$("#e663").hide();
	$("#e664").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e61').css("borderBottom","0px").animate({	});
	$('#e62').css("borderBottom", "1px solid #000000").animate({    });
	$('#e63').css("borderBottom", "1px solid #000000").animate({    });
	$('#e64').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont7').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").show();
	$("#e771").show();	
    	$("#e772").hide();
	$("#e773").hide();
	$("#e774").hide();
	$("#e8").hide();
	$('#e71').css("borderBottom","0px").animate({	});
	$('#e72').css("borderBottom", "1px solid #000000").animate({    });
	$('#e73').css("borderBottom", "1px solid #000000").animate({    });
	$('#e74').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#cont8').click(function() {
     	$("#e1").hide();
        $("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").show();
	$("#e881").show();
    	$("#e882").hide();
	$("#e883").hide();
	$("#e884").hide();
	$('#e81').css("borderBottom","0px").animate({	});
	$('#e82').css("borderBottom", "1px solid #000000").animate({    });
	$('#e83').css("borderBottom", "1px solid #000000").animate({    });
	$('#e84').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e11').click(function() {
     	$("#e111").show();
        $("#e112").hide();
	$("#e113").hide();
	$("#e114").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e11').css("borderBottom","0px").animate({	});
	$('#e12').css("borderBottom", "1px solid #000000").animate({    });
	$('#e13').css("borderBottom", "1px solid #000000").animate({    });
	$('#e14').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e12').click(function() {
     	$("#e111").hide();
                  $("#e112").show();
	$("#e113").hide();
	$("#e114").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e11').css("borderBottom", "1px solid #000000").animate({    });
	$('#e12').css("borderBottom","0px").animate({	});
	$('#e13').css("borderBottom", "1px solid #000000").animate({    });
	$('#e14').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e13').click(function() {
     	$("#e111").hide();
                  $("#e112").hide();
	$("#e113").show();
	$("#e114").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e13').css("borderBottom","0px").animate({	});
	$('#e12').css("borderBottom", "1px solid #000000").animate({    });
	$('#e11').css("borderBottom", "1px solid #000000").animate({    });
	$('#e14').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e14').click(function() {
     	$("#e111").hide();
                  $("#e112").hide();
	$("#e113").hide();
	$("#e114").show();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e14').css("borderBottom","0px").animate({	});
	$('#e12').css("borderBottom", "1px solid #000000").animate({    });
	$('#e13').css("borderBottom", "1px solid #000000").animate({    });
	$('#e11').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e21').click(function() {
     	$("#e221").show();
	$("#e222").hide();
	$("#e223").hide();
	$("#e224").hide();
     	$("#e1").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e21').css("borderBottom","0px").animate({	});
	$('#e22').css("borderBottom", "1px solid #000000").animate({    });
	$('#e23').css("borderBottom", "1px solid #000000").animate({    });
	$('#e24').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e22').click(function() {
     	$("#e221").hide();
	$("#e222").show();
	$("#e223").hide();
	$("#e224").hide();
     	$("#e1").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e22').css("borderBottom","0px").animate({	});
	$('#e21').css("borderBottom", "1px solid #000000").animate({    });
	$('#e23').css("borderBottom", "1px solid #000000").animate({    });
	$('#e24').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e23').click(function() {
     	$("#e221").hide();
	$("#e222").hide();
	$("#e223").show();
	$("#e224").hide();
  	$("#e1").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e23').css("borderBottom","0px").animate({	});
	$('#e22').css("borderBottom", "1px solid #000000").animate({    });
	$('#e21').css("borderBottom", "1px solid #000000").animate({    });
	$('#e24').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e24').click(function() {
	$("#e221").hide();
	$("#e222").hide();
	$("#e223").hide();
	$("#e224").show();
	$("#e1").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e24').css("borderBottom","0px").animate({	});
	$('#e22').css("borderBottom", "1px solid #000000").animate({    });
	$('#e23').css("borderBottom", "1px solid #000000").animate({    });
	$('#e21').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e31').click(function() {
     	$("#e331").show();
	$("#e332").hide();
	$("#e333").hide();
	$("#e334").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e31').css("borderBottom","0px").animate({	});
	$('#e32').css("borderBottom", "1px solid #000000").animate({    });
	$('#e33').css("borderBottom", "1px solid #000000").animate({    });
	$('#e34').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e32').click(function() {
        $("#e331").hide();
	$("#e332").show();
	$("#e333").hide();
	$("#e334").hide();
  	$("#e1").hide();
	$("#e2").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e32').css("borderBottom","0px").animate({	});
	$('#e31').css("borderBottom", "1px solid #000000").animate({    });
	$('#e33').css("borderBottom", "1px solid #000000").animate({    });
	$('#e34').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e33').click(function() {
     	$("#e331").hide();	
	$("#e332").hide();
	$("#e333").show();
	$("#e334").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e33').css("borderBottom","0px").animate({	});
	$('#e32').css("borderBottom", "1px solid #000000").animate({    });
	$('#e31').css("borderBottom", "1px solid #000000").animate({    });
	$('#e34').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e34').click(function() {
     	$("#e331").hide();	//hide();
	$("#e332").hide();
	$("#e333").hide();
	$("#e334").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e34').css("borderBottom","0px").animate({	});
	$('#e32').css("borderBottom", "1px solid #000000").animate({    });
	$('#e33').css("borderBottom", "1px solid #000000").animate({    });
	$('#e31').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e41').click(function() {
	$("#e441").show();
	$("#e442").hide();
	$("#e443").hide();
	$("#e444").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e41').css("borderBottom","0px").animate({	});
	$('#e42').css("borderBottom", "1px solid #000000").animate({    });
	$('#e43').css("borderBottom", "1px solid #000000").animate({    });
	$('#e44').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e42').click(function() {
	$("#e441").hide();
	$("#e442").show(); 
	$("#e443").hide();
	$("#e444").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e42').css("borderBottom","0px").animate({	});
	$('#e41').css("borderBottom", "1px solid #000000").animate({    });
	$('#e43').css("borderBottom", "1px solid #000000").animate({    });
	$('#e44').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e43').click(function() {
	$("#e441").hide();
	$("#e442").hide();
	$("#e443").show();
	$("#e444").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e43').css("borderBottom","0px").animate({	});
	$('#e42').css("borderBottom", "1px solid #000000").animate({    });
	$('#e41').css("borderBottom", "1px solid #000000").animate({    });
	$('#e44').css("borderBottom", "1px solid #000000").animate({    });
    });
   $('#e44').click(function() {
	$("#e441").hide();
	$("#e442").hide();
	$("#e443").hide();
	$("#e444").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e44').css("borderBottom","0px").animate({	});
	$('#e42').css("borderBottom", "1px solid #000000").animate({    });
	$('#e43').css("borderBottom", "1px solid #000000").animate({    });
	$('#e41').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e51').click(function() {
	$("#e551").show();
	$("#e552").hide();
	$("#e553").hide();
	$("#e554").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e51').css("borderBottom","0px").animate({	});
	$('#e52').css("borderBottom", "1px solid #000000").animate({    });
	$('#e53').css("borderBottom", "1px solid #000000").animate({    });
	$('#e54').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e52').click(function() {
	$("#e551").hide();
	$("#e552").show();
	$("#e553").hide();
	$("#e554").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e52').css("borderBottom","0px").animate({	});
	$('#e51').css("borderBottom", "1px solid #000000").animate({    });
	$('#e53').css("borderBottom", "1px solid #000000").animate({    });
	$('#e54').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e53').click(function() {
     	$("#e551").hide();
	$("#e552").hide();
	$("#e553").show();
	$("#e554").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e53').css("borderBottom","0px").animate({	});
	$('#e52').css("borderBottom", "1px solid #000000").animate({    });
	$('#e51').css("borderBottom", "1px solid #000000").animate({    });
	$('#e54').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e54').click(function() {
	$("#e551").hide();
	$("#e552").hide();
	$("#e553").hide();
	$("#e554").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e6").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e54').css("borderBottom","0px").animate({	});
	$('#e52').css("borderBottom", "1px solid #000000").animate({    });
	$('#e53').css("borderBottom", "1px solid #000000").animate({    });
	$('#e51').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e61').click(function() {
	$("#e661").show();
	$("#e662").hide();
	$("#e663").hide();
	$("#e664").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e61').css("borderBottom","0px").animate({	});
	$('#e62').css("borderBottom", "1px solid #000000").animate({    });
	$('#e63').css("borderBottom", "1px solid #000000").animate({    });
	$('#e64').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e62').click(function() {
    	$("#e661").hide();
	$("#e662").show();
	$("#e663").hide();
	$("#e664").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e62').css("borderBottom","0px").animate({	});
	$('#e61').css("borderBottom", "1px solid #000000").animate({    });
	$('#e63').css("borderBottom", "1px solid #000000").animate({    });
	$('#e64').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e63').click(function() {
     	$("#e661").hide();
	$("#e662").hide();
	$("#e663").show();
	$("#e664").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e63').css("borderBottom","0px").animate({	});
	$('#e62').css("borderBottom", "1px solid #000000").animate({    });
	$('#e61').css("borderBottom", "1px solid #000000").animate({    });
	$('#e64').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e64').click(function() {
     	$("#e661").hide();
	$("#e662").hide();
	$("#e663").hide();
	$("#e664").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e7").hide();
	$("#e8").hide();
	$('#e64').css("borderBottom","0px").animate({	});
	$('#e62').css("borderBottom", "1px solid #000000").animate({    });
	$('#e63').css("borderBottom", "1px solid #000000").animate({    });
	$('#e61').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e71').click(function() {
     	$("#e771").show();
	$("#e772").hide();
	$("#e773").hide();
	$("#e774").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e8").hide();
	$('#e71').css("borderBottom","0px").animate({	});
	$('#e72').css("borderBottom", "1px solid #000000").animate({    });
	$('#e73').css("borderBottom", "1px solid #000000").animate({    });
	$('#e74').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e72').click(function() {
     	$("#e771").hide();
	$("#e772").show();
	$("#e773").hide();
	$("#e774").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e8").hide();
	$('#e72').css("borderBottom","0px").animate({	});
	$('#e71').css("borderBottom", "1px solid #000000").animate({    });
	$('#e73').css("borderBottom", "1px solid #000000").animate({    });
	$('#e74').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e73').click(function() {
     	$("#e771").hide();
	$("#e772").hide();
	$("#e773").show();
	$("#e774").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e8").hide();
	$('#e73').css("borderBottom","0px").animate({	});
	$('#e72').css("borderBottom", "1px solid #000000").animate({    });
	$('#e71').css("borderBottom", "1px solid #000000").animate({    });
	$('#e74').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e74').click(function() {
     	$("#e771").hide();
	$("#e772").hide();
	$("#e773").hide();
	$("#e774").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e8").hide();
	$('#e74').css("borderBottom","0px").animate({	});
	$('#e72').css("borderBottom", "1px solid #000000").animate({    });
	$('#e73').css("borderBottom", "1px solid #000000").animate({    });
	$('#e71').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e81').click(function() {
     	$("#e881").show();
	$("#e882").hide();
	$("#e883").hide();
	$("#e884").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$('#e81').css("borderBottom","0px").animate({	});
	$('#e82').css("borderBottom", "1px solid #000000").animate({    });
	$('#e83').css("borderBottom", "1px solid #000000").animate({    });
	$('#e84').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e82').click(function() {
     	$("#e881").hide();
	$("#e882").show();
	$("#e883").hide();
	$("#e884").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$('#e82').css("borderBottom","0px").animate({	});
	$('#e81').css("borderBottom", "1px solid #000000").animate({    });
	$('#e83').css("borderBottom", "1px solid #000000").animate({    });
	$('#e84').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e83').click(function() {
     	$("#e881").hide();
	$("#e882").hide();
	$("#e883").show();
	$("#e884").hide();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$('#e83').css("borderBottom","0px").animate({	});
	$('#e82').css("borderBottom", "1px solid #000000").animate({    });
	$('#e81').css("borderBottom", "1px solid #000000").animate({    });
	$('#e84').css("borderBottom", "1px solid #000000").animate({    });
    });
    $('#e84').click(function() {
     	$("#e881").hide();
	$("#e882").hide();
	$("#e883").hide();
	$("#e884").show();
	$("#e1").hide();
	$("#e2").hide();
	$("#e3").hide();
	$("#e4").hide();
	$("#e5").hide();
	$("#e6").hide();
	$("#e7").hide();
	$('#e84').css("borderBottom","0px").animate({	});
	$('#e82').css("borderBottom", "1px solid #000000").animate({    });
	$('#e83').css("borderBottom", "1px solid #000000").animate({    });
	$('#e81').css("borderBottom", "1px solid #000000").animate({    });
    });
});